CREATE TABLE genres(
    genre_id INT         GENERATED BY DEFAULT AS IDENTITY   PRIMARY KEY,
    name     VARCHAR(60) UNIQUE                             NOT NULL
);


CREATE TABLE artists(
    artist_id INT         GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    name      VARCHAR(60) UNIQUE                            NOT NULL
);

CREATE TABLE genre_artist(
    genre_id  INT,
    artist_id INT,
    PRIMARY KEY (genre_id, artist_id),
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id),
    FOREIGN KEY (artist_id) REFERENCES artists(artist_id) 
);

CREATE TABLE albums(
    album_id INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(60) UNIQUE                           NOT NULL,
    year     INT         CONSTRAINT release_year_ranger
                         CHECK(year BETWEEN 1900 AND 2025)
);

CREATE TABLE album_artist(
    album_id  INT,
    artist_id INT,
    PRIMARY KEY (album_id, artist_id),
    FOREIGN KEY (album_id) REFERENCES albums(album_id),
    FOREIGN KEY (artist_id) REFERENCES artists(artist_id) 
);

CREATE TABLE tracks(
    track_id INT             GENERATED BY DEFAULT AS IDENTITY   PRIMARY KEY,
    name     VARCHAR(60)     UNIQUE                             NOT NULL,
    duration INT             NOT NULL,
    album_id INT,
    FOREIGN KEY (album_id) REFERENCES albums(album_id)
);

CREATE TABLE compilations(
    compilation_id INT         GENERATED BY DEFAULT AS IDENTITY   PRIMARY KEY,
    name           VARCHAR(60) UNIQUE                             NOT NULL,
    year           INT         CONSTRAINT release_year_ranger
                               CHECK(year BETWEEN 1900 AND 2025)
);

CREATE TABLE track_compilation(
    track_id       INT,
    compilation_id INT,
    PRIMARY KEY (track_id, compilation_id),
    FOREIGN KEY (track_id) REFERENCES tracks(track_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(compilation_id) 
);